linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  enable:
    - govet
    - copyloopvar
    - protogetter
    - typecheck
  disable:
    - wrapcheck
    - ireturn
    - varnamelen
    - gofumpt
    - goimports
    - godot
    - gci
    - revive
    - exhaustruct
    - lll
    - rowserrcheck
    - wastedassign
    - nonamedreturns
    - depguard
    - godox
    - nlreturn
    - nolintlint
    - gomoddirectives
linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 7
    # The maximal average package complexity.
    # If it's higher than 0.0 (float) the check is enabled
    # Default: 0.0
    package-average: 7.0
    # Should ignore tests.
    # Default: false
    skip-tests: true
run:
  build-tags:
    - codeanalysis